### ISSUE TITLE
Using agent app widget SDK from an Angular app

### ISSUE THREAD

**Issue by ozdave** [livechat/agent-app-widget-sdk#2] opened 2018-05-20 23:58 UTC
Hi

We are developing an Angular app with REST backend for integration with Agent App Widget. Developing in Visual Studio, app is deployed to Azure.

We could not get SDK as provided from npm to work with Angular, so we redeveloped it as an Angular service integrated with our app.

The app correctly displays in the widget pane, we can get teh plugin id, and we can also post messages to the chat using the putmessage() method, so we are confident that the app is basically correct and working.

The problem we have is we are not receiving event messages. The event listener is being added in the init() method using:
   window.addEventListener('message', this.messagesListener);

If we run the app in a browser window, we can see that the event listener is being called there. It is only within the agent widget window that it does not seem to work.

Any suggestions?

Regards

David

**Comment by fjaskolski** [comment] 2018-06-05 10:05
Hello @ozdave !

Thank you for your patience and apologies for such a delay.

I've tried to reproduce your issue by pasting the following snippet right in the browser's console:

```js
window.addEventListener('message', e => console.log(e))
```

It prints out the events right away:

<img width="484" alt="screen shot 2018-06-05 at 11 51 58" src="https://user-images.githubusercontent.com/5114422/40968911-f44ad316-68b6-11e8-9e10-a6e10e75bdd0.png">

Please let me know if it behaves the same way on your side. Keep in mind that the snippet should be pasted within the scope of your widget iframe (selected from the pink dropdown on the screen).

Could you please provide me with more details on your use case?
- What events are you expecting to show up?
- What browser did you use? There were bugs reported for particular versions of IE/Edge.
- I'm also curious what went wrong while using the npm package of this SDK in Angular App?

If you're open to [live chat](https://www.livechatinc.com/contact/) the case with me, please feel free to ask for transfer to Filip.

**Comment by quarties** [comment] 2019-03-20 12:33
@fjaskolski @ozdave I'm closing this issue as there are no new messages since Jun 2018.

**Closed by quarties** 2019-03-20 12:33 UTC
